name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy main.py to Remote Server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          source: "main.py"  # Изменено: только копирование main.py
          target: "/opt/translate"  # Путь на удаленном сервере

      - name: Install Dependencies on Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            cd /opt/translate
            # Установка pip, если он не установлен
            sudo apt-get update
            sudo apt-get install -y python3-pip

            # Установка зависимостей через pip
            python -m pip install --upgrade pip
            pip install -r requirements.txt

            # Перезапуск сервиса
            sudo systemctl restart translate.service
